# Generated by Django 4.1.7 on 2023-03-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrika', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='website',
            field=models.CharField(max_length=255),
        ),
    ]
